name: Render Map

on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Write Debfile
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ runner.temp }}/Debfile
          contents: |
            package https://github.com/koordinates/kart/releases/download/v0.15.2/kart_0.15.2_amd64.deb
          write-mode: overwrite
      - name: Install Kart
        uses: knu/apt-bundle@v1
        with:
          debfile: ${{ runner.temp }}/Debfile
      - name: Get data
        run: kart clone https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git ${{ runner.temp }}/kart-repo --workingcopy-location=${{ runner.temp }}/data.gpkg --quiet
      - name: Checkout ref
        run: kart checkout ${{github.sha}}
        working-directory: ${{ runner.temp }}/kart-repo
      - name: Install python requirements
        run: pip install geopandas matplotlib ascii_magic
      - name: Render map
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import geopandas as gpd
            import matplotlib.pyplot as plt
            from ascii_magic import AsciiArt

            plt.style.use("dark_background")

            fig, ax = plt.subplots(figsize=(10, 10))
            ax.set_axis_off()
            ax.autoscale_view("tight")
            plt.tight_layout()

            temp_dir = os.environ["RUNNER_TEMP"]

            data_layers = gpd.list_layers(f"{temp_dir}/data.gpkg")
            layer_names = data_layers.loc[:, "name"].values

            for layer_name in layer_names:
                data_frame = gpd.read_file(f"{temp_dir}/data.gpkg", layer=layer_name)
                plot = data_frame.plot(ax=ax, color="white", linewidth=0.5)

            plt.savefig(f"{temp_dir}/output.png")

            my_art = AsciiArt.from_image(f"{temp_dir}/output.png")
            outdata = my_art.to_terminal(columns=96, monochrome=True, width_ratio=2.5)
            outdata = outdata.replace("```", "`-`")

            with open(f"{temp_dir}/output.txt", "w") as f_out:
                f_out.write(f"Rendered map from:\n")
                for layer_name in layer_names:
                    f_out.write(f" * {layer_name}\n")
                f_out.write(f"```\n{outdata}\n```")
      - name: Save render
        uses: actions/upload-artifact@v4
        with:
          path: ${{ runner.temp }}/output.png
      - name: Comment
        uses: peter-evans/commit-comment@v3
        with:
          body-path: ${{ runner.temp }}/output.txt
